Repository UOU-Alarm-it/Android, pull requests merged in 2025-01, with the labels that each got.

#6 [Feat] Splash
  app/src/main/java/com/example/uou_alarm_it/SplashActivity.kt
Labels: 🛠️Feature

#8 [bug] bug
  .idea/deploymentTargetSelector.xml
  .idea/kotlinc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/uou_alarm_it/NoticeActivity.kt
  app/src/main/res/layout/activity_notice.xml
Labels: 🪛Bug

#12 [API] Retrofit
  app/build.gradle
  app/src/main/java/com/example/uou_alarm_it/RetrofitClient.kt
  app/src/main/java/com/example/uou_alarm_it/RetrofitService.kt
  gradle/libs.versions.toml
Labels: 🛜API

#16 [Feat] Bookmark
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/uou_alarm_it/NoticeActivity.kt
  app/src/main/java/com/example/uou_alarm_it/NoticeRVAdapter.kt
Labels: 🛠️Feature

#18 [API] api start
  app/src/main/java/com/example/uou_alarm_it/GetNoticeRequest.kt
  app/src/main/java/com/example/uou_alarm_it/Notice.kt
  app/src/main/java/com/example/uou_alarm_it/NoticeActivity.kt
  app/src/main/java/com/example/uou_alarm_it/NoticeRVAdapter.kt
  app/src/main/java/com/example/uou_alarm_it/RetrofitClient.kt
  app/src/main/java/com/example/uou_alarm_it/RetrofitService.kt
Labels: 🛜API

#22 [Feat] Bookmark
  app/src/main/java/com/example/uou_alarm_it/NoticeActivity.kt
Labels: 🛠️Feature

#24 [API] Search
  app/src/main/java/com/example/uou_alarm_it/NoticeActivity.kt
  app/src/main/java/com/example/uou_alarm_it/RetrofitService.kt
Labels: 🛜API

#26 [Feat] Search
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/uou_alarm_it/NoticeActivity.kt
Labels: 🛠️Feature

#28 [Feat] item Click
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/uou_alarm_it/NoticeActivity.kt
  app/src/main/java/com/example/uou_alarm_it/SplashActivity.kt
  app/src/main/java/com/example/uou_alarm_it/WebActivity.kt
  app/src/main/res/layout/activity_web.xml
Labels: 🛠️Feature

#31 [Feat] Webview
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/uou_alarm_it/WebActivity.kt
  app/src/main/res/layout/activity_web.xml
Labels: 🛠️Feature

#35 [Xml] modify xml
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/uou_alarm_it/NoticeActivity.kt
  app/src/main/res/drawable/bg_notice_date.xml
  app/src/main/res/drawable/bg_notice_search.xml
  app/src/main/res/drawable/close_search.xml
  app/src/main/res/drawable/edittext_cusor.xml
  app/src/main/res/drawable/logo.png
  app/src/main/res/drawable/logo_notice.xml
  app/src/main/res/drawable/logo_splash.xml
  app/src/main/res/drawable/uou_logo.png
  app/src/main/res/layout/activity_notice.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/item_notice.xml
  app/src/main/res/values/colors.xml
Labels: 📱Xml
